POST http://localhost:8080/api/protected HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYTY0YjY4ZDZiNTNkZjBmYTAyMWY4IiwiZW1haWwiOiJwdW50c2FnQGdtYWlsIiwiaWF0IjoxNjc5NDU4NjY4LCJleHAiOjE2Nzk1NDUwNjh9.Nh54zP_EZ8ZBr3UQTyndX5aXs_BFSHASxtd7j98GVJU"
}

###

POST http://localhost:8080/api/unprotected HTTP/1.1
Content-Type: application/json

{
    "token": ""
}

###

